databases:
  - name: ghouenzen-db
    plan: free
    databaseName: ghouenzen_db
    user: ghouenzen_user

services:
  - type: web
    name: ghouenzen
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ghouenzen-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
